/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package widget;

import complex.Complex;
import complex.evaluator.Evaluator;
import complex.evaluator.exceptions.EvaluatorParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Will
 */
public class CalculatorDialog extends javax.swing.JDialog 
{    
    /**
     * Creates new form CalculateDialog
     * @param parent the parent of this dialog
     */
    public CalculatorDialog(MainFrame parent) 
    {
        super(parent, false);
        initComponents();
        
        txtFormula.setText(parent.getCurrentEvaluator().getEquation());
        txtInput.setText("0");
        lblOutput.setText(parent.getCurrentEvaluator().f(new complex.Complex()).toAccurateString());
        lblColor.setBackground(parent.getCurrentEvaluator().f(new complex.Complex()).color());
        
        super.setTitle("Calculator");
        super.setLocation(parent.getX() + parent.getWidth() / 2 - super.getWidth() / 2, parent.getY() + parent.getHeight()/ 2 - super.getHeight()/ 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFormula = new javax.swing.JTextPane();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txtInput.setText("jTextField1");

        lblColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblColor.setOpaque(true);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtFormula);

        lblOutput.setBackground(new java.awt.Color(255, 255, 255));
        lblOutput.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblOutput.setText("jLabel1");
        lblOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 138, 153)));
        lblOutput.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 216, Short.MAX_VALUE)
                        .addComponent(btnCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOutput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnCancel))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        Evaluator eval = new Evaluator();
        
        try 
        {
            eval.setString(txtInput.getText());
        }
        catch (EvaluatorParseException e)
        {
            JOptionPane.showMessageDialog(this, "Error in input box: " + e.getMessage(), "Input box error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Complex z = eval.f(new Complex());
        
        try 
        {
            eval.setString(txtFormula.getText());
        }
        catch (EvaluatorParseException e)
        {
            JOptionPane.showMessageDialog(this, "Error in equation: " + e.getMessage(), "Equation error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Complex result = eval.f(z);
        
        lblOutput.setText(result.toAccurateString());
        lblColor.setBackground(result.color());
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        super.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCancel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JTextPane txtFormula;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
