/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package widget;

import complex.evaluator.Evaluator;
import complex.Landscape;
import complex.Complex;
import complex.History;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JToolBar;

/**
 * Main frame showing ComplexComponent
 * @author Will
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * ComplexComponent widget responsible for drawing complex landscapes an handling
     * mouse events
     */
    private final ComplexComponent _canvas;
    
    /**
     * History class responsible for keeping track of undo/redo history
     */
    private History<Landscape> _history;

    /**
     * Creates new MainFrame form
     */
    public MainFrame() {
        
        _history = new History();
        
        //Add first landscape, using a default Evaluator
        _history.add(new Landscape(new Evaluator(), new Complex(-10,-10), new Complex(10,10)));
        
        //Initialise ComplexComponent with first landscape
        _canvas = new ComplexComponent(_history.getCurrent());
        
        //Setup physical attributes for ComplexComponent and frame
        _canvas.setLayout(new BorderLayout());
        _canvas.setLocation(10, 10);
        
        super.setDefaultCloseOperation(EXIT_ON_CLOSE);
        super.setSize(1800, 1000);
        super.setVisible(true);
        
        super.setMinimumSize(new java.awt.Dimension (200, 200));
        
        initComponents();
        
        CanvasPane.add(_canvas);
    }
    
    @Override
    public void paint(java.awt.Graphics g) 
    { 
        if (_canvas != null && CanvasPane != null)
            _canvas.setSize( CanvasPane.getWidth() - 20 , CanvasPane.getHeight() - 20); 
        super.paint(g); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPane = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPan = new javax.swing.JButton();
        btnZoom = new javax.swing.JButton();
        btnNewton = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        btnZoomIn = new javax.swing.JButton();
        btnZoomOut = new javax.swing.JButton();
        CanvasPane = new javax.swing.JPanel();
        StatusPane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/new.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        MenuPane.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 28));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/save.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        MenuPane.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 30, 28));

        btnPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/pan.png"))); // NOI18N
        btnPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanActionPerformed(evt);
            }
        });
        MenuPane.add(btnPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, 30, 28));

        btnZoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/zoom.png"))); // NOI18N
        btnZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomActionPerformed(evt);
            }
        });
        MenuPane.add(btnZoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 0, 30, 28));

        btnNewton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/newton.png"))); // NOI18N
        btnNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewtonActionPerformed(evt);
            }
        });
        MenuPane.add(btnNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 0, 30, 28));

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/undo.png"))); // NOI18N
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        MenuPane.add(btnUndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 28));

        btnRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/redo.png"))); // NOI18N
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });
        MenuPane.add(btnRedo, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 30, 28));

        btnZoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/zoomin.png"))); // NOI18N
        btnZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomInActionPerformed(evt);
            }
        });
        MenuPane.add(btnZoomIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, 30, 28));

        btnZoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbar/zoomout.png"))); // NOI18N
        btnZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomOutActionPerformed(evt);
            }
        });
        MenuPane.add(btnZoomOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 0, 30, 28));

        javax.swing.GroupLayout CanvasPaneLayout = new javax.swing.GroupLayout(CanvasPane);
        CanvasPane.setLayout(CanvasPaneLayout);
        CanvasPaneLayout.setHorizontalGroup(
            CanvasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1762, Short.MAX_VALUE)
        );
        CanvasPaneLayout.setVerticalGroup(
            CanvasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout StatusPaneLayout = new javax.swing.GroupLayout(StatusPane);
        StatusPane.setLayout(StatusPaneLayout);
        StatusPaneLayout.setHorizontalGroup(
            StatusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1762, Short.MAX_VALUE)
        );
        StatusPaneLayout.setVerticalGroup(
            StatusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CanvasPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StatusPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CanvasPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZoomOutActionPerformed

    private void btnZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZoomInActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        // TODO add your handling code here:
        if (!_history.isAtTop())
        {
            _history.redo();
            _canvas.setLandscape(_history.getCurrent());
            _canvas.repaint();
        }
    }//GEN-LAST:event_btnRedoActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        System.out.println("Pointer: " + _history.getPointer() + ", Size: " + _history.toArray().length + "Res: " + (!_history.isAtBottom()));
        if (!_history.isAtBottom())
        {
            _history.undo();
            _canvas.setLandscape(_history.getCurrent());
            _canvas.repaint();
        }
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnNewtonActionPerformed

    private void btnZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnZoomActionPerformed

    private void btnPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPanActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        PropertyDialog d = new PropertyDialog(this, _history.getCurrent());

        if (d.isAccepted())
        {
            _history.add(d.getLandscape());
            _canvas.setLandscape(_history.getCurrent());
            _canvas.repaint();
        }

        System.out.println(_history.toString());
    }//GEN-LAST:event_btnNewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CanvasPane;
    private javax.swing.JPanel MenuPane;
    private javax.swing.JPanel StatusPane;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNewton;
    private javax.swing.JButton btnPan;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private javax.swing.JButton btnZoom;
    private javax.swing.JButton btnZoomIn;
    private javax.swing.JButton btnZoomOut;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
